### ISSUE TITLE
Support DCMS on content planning esp. for charts

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/DCMS#25]
Once content planning is underway we can begin to define SPARQL queries to source data for the charts

**Comment by charlesons** [comment]
In planning session 20/09/22 we decided that on completing this discovery process and we can then proceed to create tickets for each page or dashboard of content. Those tickets would have sub-tasks related to creating the content.

**Comment by TahaRana97** [comment]
session delivered on 29/09
