### ISSUE TITLE
SPARQL queries for PmD

### ISSUE THREAD

**Issue by TahaRana97** [GSS-Cogs/DCMS#27]

**Comment by RedWalters** [comment]
Sparql queries for all the graphs on the [Main Report ](https://www.gov.uk/government/statistics/participation-survey-october-to-december-2021-report/participation-survey-october-to-december-2021-main-report) (Where applicable) have been written up and can be found [Here](https://github.com/GSS-Cogs/family-participation-survey/blob/master/datasets/DCMS-Participation-Survey-2021-22-annual-data-tables/sparql-queries.sparql)
