### ISSUE TITLE
CMS Implementation / Architecture

### ISSUE THREAD

**Issue by anojperera** [GSS-Cogs/DCMS#8]

**Comment by anojperera** [comment]
This ticket is to establish and implement the infrastructure required for DCMS CMS.
My preference is to have it implemented as a complete separate stack. This way we do not have a single point of failure for all sites.  We are already using artefacts (Plone / Volto) to pull into the VM therefore this will not be an issue if we were to have separate stack. Although it is separate stack the components and artefacts i.e. the code base shall be the same. Ultimate this is to be wetted by @ajtucker @eldeal

**Comment by eldeal** [comment]
I have concerns about the sustainability of taking a separate stack approach. While I can appreciate the isolation this gives us, when we have dozens of different dashboards will we really be able to maintain dozens of stacks? 

If we need to roll out an update to the CMS, we would have to roll that update across dozens of services which introduces a wider number of opportunities for things to go wrong. In the future I expect we'll have centralized logging and monitoring in place, and for this we'd need to include some additional indicator of which instance it is the logs are coming from (achievable) and whenever a user reports an issue we'd need to be sure we know which instance they're reporting issue with. Every time we get a bug we'd have to do an additional level of analysis about whether this is an issue just in that stack/with that configuration or whether it's a common application problem. 

I worry that the complexity managing multiple stacks add is not worth the benefit of more isolated failure. There are other mitigations for those kinds of failures that I think would come with fewer drawbacks personally.

**Comment by eldeal** [comment]
I need clarity on requirements though: is there a _requirement_ that each dashboard is hosted on its' own subdomain? Or could they be different endpoints on the same domain? Because that certainly impacts the direction

**Comment by anojperera** [comment]
Thats a very valid concern you have raised with regards to maintaining multiple stacks. These days we have good matured tools for doing just that such as Ansible. Alternatively we can use a simple bash script to execute via a pipeline. Having everything in one stack introduces a single point of failure. In the unlikely event that we do end up with a breakage we will bring all sites down which is not ideal. Also when we say multiple stacks, they shall be identical. All of the above is independent of DNS configurations.

![Plone Volto-Page-5.png](https://images.zenhubusercontent.com/619f67e36a20872245102c1c/1bffc437-bb48-4904-80cc-e1852c610924)

**Comment by charlesons** [comment]
For scaleable storage it may be worth looking into [Relstorage](Relstorage over the weekend that allows Plone to use relational DBs for storage  https://docs.google.com/presentation/d/1zeJ7MiMitejAdSSUkntHrqHs_Iu9h4q1vYJ1GwQbnpI/htmlpresent)

**Comment by eldeal** [comment]
I think we're happy that this is done now? We have 1 production k8s cluster and plone manages subsites in the postgres DB within that. There is a DCMS site in the DB now

**Comment by eldeal** [comment]
Unless there are any outstanding questions, this can move to done
